In [2]:
import numpy as np

In [3]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix = np.array([[i*j for i in range(1,21)] for j in range(1 , 11)])
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60,  64,  68,  72,  76,  80],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90,  96, 102, 108, 114, 120],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105, 112, 119, 126, 133, 140],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120, 128, 136, 144, 152, 160],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 1

In [18]:
parts = 11
s = matrix.shape
splitParts = [matrix[:,i*s[1]//parts:(i+1)*s[1]//parts] for i in range(parts)]
splitParts

[array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[ 2,  3],
        [ 4,  6],
        [ 6,  9],
        [ 8, 12],
        [10, 15],
        [12, 18],
        [14, 21],
        [16, 24],
        [18, 27],
        [20, 30]]),
 array([[ 4,  5],
        [ 8, 10],
        [12, 15],
        [16, 20],
        [20, 25],
        [24, 30],
        [28, 35],
        [32, 40],
        [36, 45],
        [40, 50]]),
 array([[ 6,  7],
        [12, 14],
        [18, 21],
        [24, 28],
        [30, 35],
        [36, 42],
        [42, 49],
        [48, 56],
        [54, 63],
        [60, 70]]),
 array([[ 8,  9],
        [16, 18],
        [24, 27],
        [32, 36],
        [40, 45],
        [48, 54],
        [56, 63],
        [64, 72],
        [72, 81],
        [80, 90]]),
 array([[ 10],
        [ 20],
        [ 30],
        [ 40],
        [ 50],
        [ 60],
        [ 70],
        [ 80],
        [ 

In [ ]:
l = splitParts